### ISSUE TITLE
Upload some codes

### ISSUE THREAD

**Issue by aman-raza** [aman-raza/Friends_Hack#1]
Meaningful Codes only
Must include multiple functions or methods

**Comment by lostgirljourney** [comment]
@aman-raza elaborate... 👀

**Comment by aman-raza** [comment]
upload any code as u wish

**Comment by venkateshpensalwar** [comment]
can i upload c++ codes like if..else or loops or like count characters in string

**Comment by kubercodes** [comment]
Hey @aman-raza can I contribute in it.

**Comment by Ansh04122001** [comment]
can i upload python codes for voice assitants

**Comment by jyotiGambhir** [comment]
Can I add some CPP problems?

**Comment by anishjain94** [comment]
Updated Readme.md with Proper Instructions, Added Recursion and HTML- PR #28

**Comment by secrashi** [comment]
Hey Can I add BFS implementation code?

**Comment by simran1199** [comment]
Hi!! I have added a simple code for the scorekeeper app for games-- PR #64 . Can you please give it a check?

**Comment by aman-raza** [comment]
Ya this is open

**Comment by ssurbhi09** [comment]
I  have done you can see it and please merge it thanyou.

**Comment by ssurbhi09** [comment]
What problem with my code can you please explain

**Comment by aman-raza** [comment]
you must create a pr without deleting the codes from the main branch or you can create a pr by creating another branch

**Comment by Ankita-Nandkumar-Patil** [comment]
can i still contribute here for hactoberfest..?
will you please suggest or assign me some task @aman-raza ..!
