### ISSUE TITLE
Put any C , C++ , Python or JavaScript codes

### ISSUE THREAD

**Issue by aman-raza** [aman-raza/Friends_Hack#19]

**Comment by amitsat27** [comment]
@aman-raza can i add merge sort and quick sort ?

**Comment by ayu16** [comment]
I can put python codes in whichever you want

**Comment by DhruvSondhi** [comment]
can i contribute sorting and searching algorithms code in C++ ?

**Comment by aman-raza** [comment]
yes u can put any codes

**Comment by Ansh04122001** [comment]
can i add  some python   code for tic tac toe

**Comment by imsubhra** [comment]
I have added Tower of Hanoi code and please merge it @aman-raza

**Comment by Ansh04122001** [comment]
can i add 30 day hackerrank code for (c++)

**Comment by Dutta-SD** [comment]
Hi,
Can I add some graph and tree algorithms @aman-raza ?

**Comment by ananya0504** [comment]
I have coded various competitive coding questions in C++. Can I add the codes here?

**Comment by deepdhar** [comment]
@aman-raza I'm adding Fibonacci series code in C

**Comment by kartickgupta** [comment]
Can I add Binary Tree and BST questions in C++ ?

**Comment by ananya0504** [comment]
I added some codes. But I by mistake put them in the wrong extension. Can something be done?

**Comment by Anuragkar234** [comment]
Can I contribute in Golang??

**Comment by Chaitalykundu** [comment]
I'm adding a Fizzbuzz game

**Comment by satcasm** [comment]
@aman-raza I had added  Creation and deletion of circular linked list yesterday . Please review it.

**Comment by satcasm** [comment]
@aman-raza please review my PR. #59

**Comment by aritrochakraborty29** [comment]
want to add some codes..
can you please assign me?

**Comment by Chaitali3005** [comment]
Can you assign me this issue to add C programs?

**Comment by rutuja060** [comment]
Can you assign me to add some c++ codes?

**Comment by Chaitali3005** [comment]
Please review my code and merge the request

**Comment by sarthak-1503** [comment]
Can you assign me this issue?? I will contribute in c++

**Comment by Sindhu-321** [comment]
Can I contribute if this is still open?

**Comment by aman-raza** [comment]
yes u can

**Comment by Vrushti24** [comment]
Is this issue still open for hacktoberfest2021 @aman-raza  ?? would love to contribute my code in this

**Comment by aman-raza** [comment]
yup good to go

**Comment by Yash2001340** [comment]
this repository is excluded from hactoberfest  2021
