### ISSUE TITLE
Upload some simple game codes

### ISSUE THREAD

**Issue by aman-raza** [aman-raza/Friends_Hack#69]

**Comment by Kartik987** [comment]
hey @aman-raza . Can i contribute to this?

**Comment by aman-raza** [comment]
yes u r welcome

**Comment by aritrochakraborty29** [comment]
Want to add some cool games

**Comment by Rinevitable** [comment]
i have pulled #77 but it didn't got merged .
have a look .
any suggestion will be appreciated

**Comment by Rinevitable** [comment]
i have pulled #77 but it didn't got merged .
have a look @aman-raza .
any suggestion will be appreciated

**Comment by abhishek351** [comment]
Yeah  can i import GUI calculator (python). its a great projects for beginners.

**Comment by NANDINII-ROCKS** [comment]
I can contribute a good Flutter Game!
